#!/usr/bin/env bash

# Shaws the last lines of a file for as long as a named process runs.
# By default, wsk-*.log files and python3.
#
# Run:
#
#   ./watcher.py
#   ./watcher.py wsk-20180101.log
#   ./watcher.py wsk-20180101.log myprocess

DEFAULT_LOG="wsk*.log"
LOG=${1:-$DEFAULT_LOG}

DEFAULT_PNAME="python3"
PNAME=${2:-$DEFAULT_PNAME}

# The script currently uses "python3" (rather than "searchcmd.py")
# due to limitations of pidof.

watch -n 5 -e "ps -fw -p $(pidof ${PNAME}) && echo && tail -n 5 ${LOG}"

# watch          refresh a group of commands
# -n 5           every 5 seconds,
# -e             and stop if it returns an error
# " "            on a group of commands
#  ps            list processes
#  -fw           with formatting that shows the full command
#  -p            for specific process id(s) list
#  $(pidof x)    which are retrieved by command name
# &&             and
# echo           print a blank line
# &&             and
# tail -n 5      the last 5 lines of the file(s)
